name: kesh_kart
description: "Kesh Kart"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  provider: ^6.1.1
  crypto: ^3.0.6

  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0
  glowy_borders: ^1.0.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  http: ^1.3.0
  geolocator: ^13.0.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.3
  web_socket_channel: ^3.0.3
  my_baas_sdk:
    path: ../my_baas_sdk
  geocoding: ^4.0.0
  google_fonts: ^6.2.1
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.2
  flutter_secure_storage: ^9.2.2
  app_device_integrity: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

  # Removed unnecessary dev dependency on flutter_launcher_icons

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/mustache.png
    - assets/images/barber.png
    - assets/images/customer.png
    - assets/images/flag.png
    - assets/images/image1.png
    - assets/images/otp.png
    - assets/images/SignUp.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/haircut.png
    - assets/images/noise.png
    - assets/styles/
    - assets/faces/oval/
    - assets/faces/round/
    - assets/faces/square/
    - assets/faces/heart/
    - assets/faces/diamond/
    - assets/hairstyles/textured_fade/
    - assets/hairstyles/undercut/
    - assets/hairstyles/pompadour/
    - assets/hairstyles/quiff/
    - assets/hairstyles/crew_cut/
    - assets/hairstyles/side_part/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Popins
      fonts:
        # - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
          style: normal

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
