// File generated by BaaS Console (Manual Copy for now)
// Defines the project keys for each platform.

import 'backend/baas_env_config.dart';

class DefaultBaasOptions {
  static String get apiUrl => BaasEnvConfig.current.apiUrl;

  // Platform-specific Project Keys
  static String get androidKey => BaasEnvConfig.current.androidProjectKey;
  static String get webKey => BaasEnvConfig.current.androidProjectKey;
  static String get windowsKey => BaasEnvConfig.current.androidProjectKey;
  static String get iosKey => BaasEnvConfig.current.androidProjectKey;

  // Realtime
  static String get realtimeUrl => BaasEnvConfig.current.realtimeUrl;
}
