// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5JDQuDNbYK4pS2ImuXK_E2htpKbIQpmM',
    appId: '1:30729698212:web:feba3aa616df62a750df31',
    messagingSenderId: '30729698212',
    projectId: 'kesh-kart',
    authDomain: 'kesh-kart.firebaseapp.com',
    storageBucket: 'kesh-kart.firebasestorage.app',
    measurementId: 'G-N7S5QDKECT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPZSbb53R3bIvWEkuRXqa33yKxkrV5vE',
    appId: '1:30729698212:android:4d222e589142f4fe50df31',
    messagingSenderId: '30729698212',
    projectId: 'kesh-kart',
    storageBucket: 'kesh-kart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmirTC3GY19EBIsVcIPIug5rD1w714MRI',
    appId: '1:30729698212:ios:45ac8ee51dbabdbb50df31',
    messagingSenderId: '30729698212',
    projectId: 'kesh-kart',
    storageBucket: 'kesh-kart.firebasestorage.app',
    androidClientId: '30729698212-2nn99lq4vl98ec6kfk36g3a9ghdii727.apps.googleusercontent.com',
    iosClientId: '30729698212-juroqlpbphqcmptia3od90q8psk0187o.apps.googleusercontent.com',
    iosBundleId: 'com.example.keshKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmirTC3GY19EBIsVcIPIug5rD1w714MRI',
    appId: '1:30729698212:ios:45ac8ee51dbabdbb50df31',
    messagingSenderId: '30729698212',
    projectId: 'kesh-kart',
    storageBucket: 'kesh-kart.firebasestorage.app',
    androidClientId: '30729698212-2nn99lq4vl98ec6kfk36g3a9ghdii727.apps.googleusercontent.com',
    iosClientId: '30729698212-juroqlpbphqcmptia3od90q8psk0187o.apps.googleusercontent.com',
    iosBundleId: 'com.example.keshKart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5JDQuDNbYK4pS2ImuXK_E2htpKbIQpmM',
    appId: '1:30729698212:web:21446d1f9a4fc9f150df31',
    messagingSenderId: '30729698212',
    projectId: 'kesh-kart',
    authDomain: 'kesh-kart.firebaseapp.com',
    storageBucket: 'kesh-kart.firebasestorage.app',
    measurementId: 'G-2245KMW1Q0',
  );

}